apiVersion: v1
kind: Namespace
metadata:
  name: lab-tvb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-tvb
  namespace: lab-tvb
  labels:
    app: backend-nest-tvb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-tvb
  template:
    metadata:
      labels:
        app: backend-nest-tvb
    spec:
      containers:
        - name: backend-nest-tvb
          image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-tvb
          imagePullPolicy: Always